//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDatVeXemPhim
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class moviedbEntities : DbContext
    {
        public moviedbEntities()
            : base("name=moviedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Movy> Movies { get; set; }
        public virtual DbSet<SelectPos> SelectPos { get; set; }
        public virtual DbSet<Showtime> Showtimes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual ObjectResult<string> sp_Chodaconguoi(Nullable<int> maPhim, string xuatchieu)
        {
            var maPhimParameter = maPhim.HasValue ?
                new ObjectParameter("MaPhim", maPhim) :
                new ObjectParameter("MaPhim", typeof(int));
    
            var xuatchieuParameter = xuatchieu != null ?
                new ObjectParameter("Xuatchieu", xuatchieu) :
                new ObjectParameter("Xuatchieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_Chodaconguoi", maPhimParameter, xuatchieuParameter);
        }
    }
}
