//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDatVeXemPhim
{
    using System;
    using System.Collections.Generic;
    
    public partial class Showtime
    {
        public int num { get; set; }
        public int MovieID { get; set; }
        public Nullable<int> ShowTime1 { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public Nullable<int> Seat { get; set; }
        public Nullable<int> Theater { get; set; }
    
        public virtual Movy Movy { get; set; }
    }
}
